### ISSUE TITLE
bug: Cannot submit when duplicated pokemon exists

### ISSUE THREAD

**Issue by lacolaco** [potato4d/pokemon63#19]
![image](https://user-images.githubusercontent.com/1529180/81464331-945a8300-91fb-11ea-9a4d-f8244e10f07c.png)

解析の結果同一のポケモンが複数存在するとき、選出順が重複してしまい取り込むことができない

**Comment by potato4d** [comment]
今日のリリースで修正機能を実装することで対処しました🙏
