### ISSUE TITLE
bug: Umbreon is recognized as Noctowl often

### ISSUE THREAD

**Issue by lacolaco** [potato4d/pokemon63#20]
ブラッキーがよくヨルノズクになる

https://pokedri.com/pokemon63/record/2rkia5LIvldvEvVFmX12
https://pokedri.com/pokemon63/record/OLdIIgC6PFPxXBBkHldQ

**Comment by potato4d** [comment]
@lacolaco 

こちら調査しますので暫くお時間いただければと思います🙏
暫定的に訂正機能を実装したので間違いがあればそちらで解析結果を訂正いただけると幸いです。

訂正機能実装前にご報告いただいた誤検出についてはこちらでデータを差し替えておきました。

**Comment by potato4d** [comment]
#47 に対応後、デプロイ完了しました 🙏 
報告とスクリーンショット、ありがとうございました！
