### ISSUE TITLE
feat: 解析結果の修正モーダルを開いたときにテキストフィールドにフォーカスを当ててほしい

### ISSUE THREAD

**Issue by lacolaco** [potato4d/pokemon63#28]
アイコンから選ぶビューがあるが800もポケモンいたら最初からスクロールしながら探すユースケースはあまり無いと思われ、まず絞り込んでからアイコンを探すことになるので、フォーカスをテキストフィールドに当ててほしい

**Comment by potato4d** [comment]
こちら本日のリリースで対応いたしました！
