### ISSUE TITLE
bug: inputted text is cleared when uploaded an image

### ISSUE THREAD

**Issue by lacolaco** [potato4d/pokemon63#29]
画像のアップロードを行う前に下書きしておいたテキストが消えてしまう。初期リリース版では残るようになっていたので試合中にメモしながら試合後に画像をアップロードすることができたが、できなくなってしまった

**Comment by potato4d** [comment]
再アップロード時に選出が残ってしまう問題があったので、その修正でアップロード開始時に一度リセットするようにした影響かとおもいます。

メモ欄は保持するように修正します🙏

**Comment by potato4d** [comment]
修正後、リリース済みです。
ご迷惑おかけしました 🙇‍♂️

**Comment by lacolaco** [comment]
ありがとうございます！
